// flow-typed signature: d0adcb6f1e791aac88288ec021d5e6f2
// flow-typed version: <<STUB>>/connect-mongo_v1.3.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-mongo/es5' {
  declare module.exports: any;
}

declare module 'connect-mongo/src-es5/index' {
  declare module.exports: any;
}

declare module 'connect-mongo/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-mongo/es5.js' {
  declare module.exports: $Exports<'connect-mongo/es5'>;
}
declare module 'connect-mongo/index' {
  declare module.exports: $Exports<'connect-mongo'>;
}
declare module 'connect-mongo/index.js' {
  declare module.exports: $Exports<'connect-mongo'>;
}
declare module 'connect-mongo/src-es5/index.js' {
  declare module.exports: $Exports<'connect-mongo/src-es5/index'>;
}
declare module 'connect-mongo/src/index.js' {
  declare module.exports: $Exports<'connect-mongo/src/index'>;
}
