// flow-typed signature: c43f0768e47a0c6725013efdee0b8923
// flow-typed version: <<STUB>>/html-to-text_v3.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-to-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-to-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-to-text/bin/cli' {
  declare module.exports: any;
}

declare module 'html-to-text/example/html-to-text' {
  declare module.exports: any;
}

declare module 'html-to-text/lib/formatter' {
  declare module.exports: any;
}

declare module 'html-to-text/lib/helper' {
  declare module.exports: any;
}

declare module 'html-to-text/lib/html-to-text' {
  declare module.exports: any;
}

declare module 'html-to-text/test/html-to-text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-to-text/bin/cli.js' {
  declare module.exports: $Exports<'html-to-text/bin/cli'>;
}
declare module 'html-to-text/example/html-to-text.js' {
  declare module.exports: $Exports<'html-to-text/example/html-to-text'>;
}
declare module 'html-to-text/index' {
  declare module.exports: $Exports<'html-to-text'>;
}
declare module 'html-to-text/index.js' {
  declare module.exports: $Exports<'html-to-text'>;
}
declare module 'html-to-text/lib/formatter.js' {
  declare module.exports: $Exports<'html-to-text/lib/formatter'>;
}
declare module 'html-to-text/lib/helper.js' {
  declare module.exports: $Exports<'html-to-text/lib/helper'>;
}
declare module 'html-to-text/lib/html-to-text.js' {
  declare module.exports: $Exports<'html-to-text/lib/html-to-text'>;
}
declare module 'html-to-text/test/html-to-text.js' {
  declare module.exports: $Exports<'html-to-text/test/html-to-text'>;
}
