// flow-typed signature: b66f61fc904a879f34099ecf12d51e7d
// flow-typed version: <<STUB>>/mongoose-mongodb-errors_v0.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-mongodb-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-mongodb-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-mongodb-errors/lib/plugin' {
  declare module.exports: any;
}

declare module 'mongoose-mongodb-errors/specs/global.specs' {
  declare module.exports: any;
}

declare module 'mongoose-mongodb-errors/specs/lib/plugin.specs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-mongodb-errors/lib/plugin.js' {
  declare module.exports: $Exports<'mongoose-mongodb-errors/lib/plugin'>;
}
declare module 'mongoose-mongodb-errors/specs/global.specs.js' {
  declare module.exports: $Exports<'mongoose-mongodb-errors/specs/global.specs'>;
}
declare module 'mongoose-mongodb-errors/specs/lib/plugin.specs.js' {
  declare module.exports: $Exports<'mongoose-mongodb-errors/specs/lib/plugin.specs'>;
}
